create table if not exists location (
    location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name varchar(255) NOT NULL
);

create table if not exists weather_condition (
    weather_condition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_text varchar(255) NOT NULL
);

create table if not exists weather_data (
    weather_data_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    air_temperature double precision NOT NULL,
    atmosphere_pressure double precision NOT NULL,
    humidity integer NOT NULL,
    last_update timestamp NOT NULL,
    wind_speed double precision NOT NULL,
    weather_condition_id bigint NOT NULL REFERENCES weather_condition(weather_condition_id),
    location_id bigint NOT NULL REFERENCES location(location_id)
);

create table if not exists weather (
    weather_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_data_id bigint NOT NULL REFERENCES weather_data(weather_data_id)
);